export const GameList = {
    games: {
        'arma3': 'Arma 3',
        'arma2': 'Arma 2',
        'dayz': 'Dayz Standalone',
        'dayzmod': 'Dayz Mod 2013',
        'csgo': 'Counter-Strike: Global Offensive',
        'cs16': 'Counter-Strike 1.6',
        'fivem': 'FiveM',
        'samp': 'San Andreas Multiplayer',
        'mtasa': 'MTA San Andreas',
        'mtavc': 'MTA Vice City',
        'minecraft': 'Minecraft',
        'minecraftpe': 'Minecraft: Pocket Edition',
        'ps': 'Post Scriptum',
        'przomboid': 'Project Zomboid',
        'rust': 'Rust',
        'rfactor': 'rFactor',
        'squad': 'Squad',
        'valheim': 'Valheim',
        '7d2d': '7 Days to Die',
        'aoe2': 'Age of Empires 2',
        'arkse': 'Ark Survival Evolved',
        'assettocorsa': 'Assetto Corsa',
        'conanexiles': 'Conan Exiles',
        'garrysmod': 'Garry\'s Mod',
        'hll': 'Hell Let Loose',
        'insurgency': 'Insurgency',
        'insurgencysandstorm': 'Insurgency: Sandstorm',
        'killingfloor': 'Killing Floor',
        'killingfloor2': 'Killing Floor 2',
        'left4dead': 'Left 4 Dead',
        'left4dead2': 'Left 4 Dead 2',
        'openttd': 'OpenTTD',
    },
    services: {
        'teamspeak3': 'TeamSpeak 3',
        'teamspeak2': 'TeamSpeak 2',
        'ventrilo': 'Ventrilo',
        'discord': 'Discord',
    }
};
