on:
  push:
    branches:
      - develop

name: deploy bot to master infraestructure

jobs:
  deploy:
    name: Build and push image to registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Private Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: build and push to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./Dockerfile
          build-args: APP=dev
          platforms: linux/arm/v7
          tags: ${{ secrets.REGISTRY_URL }}/steamid64toguid-bot-dev:v2.0.1